/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Generation = IDL.Record({
  'id' : IDL.Text,
  'style' : IDL.Text,
  'imageUrl' : IDL.Text,
  'timestamp' : IDL.Int,
  'prompt' : IDL.Text,
});

export const idlService = IDL.Service({
  'deleteGeneration' : IDL.Func([IDL.Text], [], []),
  'getGenerations' : IDL.Func([], [IDL.Vec(Generation)], ['query']),
  'saveGeneration' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Generation], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Generation = IDL.Record({
    'id' : IDL.Text,
    'style' : IDL.Text,
    'imageUrl' : IDL.Text,
    'timestamp' : IDL.Int,
    'prompt' : IDL.Text,
  });
  
  return IDL.Service({
    'deleteGeneration' : IDL.Func([IDL.Text], [], []),
    'getGenerations' : IDL.Func([], [IDL.Vec(Generation)], ['query']),
    'saveGeneration' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Generation],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };